temp/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position_ID__c</fullName>
        <externalId>true</externalId>
        <label>Position ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>50K-75K</fullName>
                </value>
                <value>
                    <fullName>75K-90K</fullName>
                </value>
                <value>
                    <fullName>90K-120K</fullName>
                </value>
                <value>
                    <fullName>120K+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Job Advertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Resume__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position_ID__c</fullName>
        <defaultValue>&quot;text&quot;</defaultValue>
        <label>Position ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Resume</label>
    <nameField>
        <displayFormat>Resume-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/EndpointResumeTest.cls
@isTest
private class EndpointResumeTest {
    
    private static String url = System.URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/Resume__c/';
    
    static Resume__c createTestRecord() {
        Resume__c resumeTest = new Resume__c(  
            Full_Name__c = 'Name',
            Age__c = 20,
            Salary__c = 9898,
            Email__c = 'Email@gmail.com',
            Phone__c = '+3805454564564'
        );
        return resumeTest;
    }
    
    private static RestRequest getRequest(String jsonBody, String method, String requestUri){  //RestRequest для устранения дублей
		RestRequest request = new RestRequest();
		request.httpMethod = method;
		if(jsonBody!=null){
			request.requestBody = Blob.valueOf(jsonBody);
		}
		request.addHeader('Content-Type', 'application/json');
		request.requestUri = requestUri;
		RestContext.request = request;
		return request;
	}
    
    @isTest
    static void testGetJobAdvertisementId() {
    	Resume__c testRecord = createTestRecord();
        insert testRecord;
        String json = System.JSON.serialize(testRecord);
        RestRequest request = getRequest(json, 'GET', url+testRecord.Id);
        request.addParameter('Id', testRecord.Id);
        List<Resume__c> resumeList = EndpointResume.getResume();
        System.assert(resumeList != null);
        System.assertEquals(resumeList.get(0).Id, testRecord.Id);
    }
    
    //TRIGGER
    
    @isTest
    static void testUpdateStatusTrigger() {
        JobAdvertisementArchivedTriggerHelper triggerHelper = new JobAdvertisementArchivedTriggerHelper();
        
        Resume__c resume = new Resume__c(Email__c = 'test@test.com', Position_ID__c = 'text 999999');
        insert resume;
        Job_Advertisement__c testJobAdvertisement = new Job_Advertisement__c(Position_ID__c = '999999');
        insert testJobAdvertisement;
        
        System.assertEquals('text 999999', resume.Position_ID__c);
        
        testJobAdvertisement.Status__c = 'Archived';
        update testJobAdvertisement;
        
        Test.startTest();
        	triggerHelper.removePositionId(testJobAdvertisement);
        Test.stopTest();
        
        Resume__c resumeTest = [SELECT Position_ID__c FROM Resume__c WHERE Email__c = 'test@test.com'];
        System.assertEquals('text', resumeTest.Position_ID__c);
    }
    
    @isTest
    static void testDeletePositionTrigger() {
        JobAdvertisementArchivedTriggerHelper triggerHelper = new JobAdvertisementArchivedTriggerHelper();
        
        Resume__c resume = new Resume__c(Email__c = 'test@test.com', Position_ID__c = 'text 999999');
        insert resume;
        Job_Advertisement__c testJobAdvertisement = new Job_Advertisement__c(Position_ID__c = '999999');
        insert testJobAdvertisement;
        
        System.assertEquals('text 999999', resume.Position_ID__c);
        
        delete testJobAdvertisement;
        
        Test.startTest();
        	triggerHelper.removePositionId(testJobAdvertisement);
        Test.stopTest();
        
        Resume__c resumeTest = [SELECT Position_ID__c FROM Resume__c WHERE Email__c = 'test@test.com'];
        System.assertEquals('text', resumeTest.Position_ID__c);
    }
}