temp/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Position_ID__c</fullName>
        <externalId>true</externalId>
        <label>Position ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Job Advertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Resume__c.object
<CustomObject>
    <fields>
        <fullName>Position_ID__c</fullName>
        <defaultValue>&quot;text&quot;</defaultValue>
        <label>Position ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Resume</label>
    <nameField>
        <displayFormat>Resume-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/JobAdvertisementArchivedTriggerHelper.cls
public class JobAdvertisementArchivedTriggerHelper {
    
    public void removePositionId(Job_Advertisement__c jobAdvertisement){
        List<Resume__c> resumesList  = [SELECT Id, Position_ID__c FROM Resume__c];
            
        for(Resume__c resume : resumesList){
            if(resume.Position_ID__c != null && resume.Position_ID__c.contains(jobAdvertisement.Position_ID__c)){
                List<String> positionIdsList = String.valueOf(resume.Position_ID__c).split(' ');
                    
                for(Integer i=0; i<positionIdsList.size(); i++){
                    if(positionIdsList[i] == jobAdvertisement.Position_ID__c){
                        positionIdsList.remove(i);   
            		} 
                }
                resume.Position_ID__c = String.join(positionIdsList,' ');
                update resume;
            }
        }
    }
}