temp/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAX_Salary__c</fullName>
        <formula>IF(CONTAINS(TEXT(Salary__c),&quot;+&quot;),
    VALUE(&quot;9999999999999999&quot;),
    VALUE(TRIM(LEFT(MAX_Salary_helper__c, FIND(&quot;K&quot;, MAX_Salary_helper__c)-1))+&quot;000&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAX Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MIN_Salary__c</fullName>
        <formula>VALUE(TRIM(LEFT(TEXT(Salary__c), FIND(&quot;K&quot;, TEXT(Salary__c))-1))+&quot;000&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MIN Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>50K-75K</fullName>
                </value>
                <value>
                    <fullName>75K-90K</fullName>
                </value>
                <value>
                    <fullName>90K-120K</fullName>
                </value>
                <value>
                    <fullName>120K+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Temporary_Status__c</fullName>
        <label>Temporary Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Job Advertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/JobAdvertisementController.cls
public class JobAdvertisementController{
    public Integer size{get;set;} 
    public Integer noOfRecords{get; set;}
    public Integer equalSalary{get;set;}
    public Integer notEqualSalary{get;set;}
    public Integer lessThanSalary{get;set;}
    public Integer lessThanEqualSalary{get;set;}
    public Integer moreThanSalary{get;set;}
    public Integer moreThanEqualSalary{get;set;}
    
    public String soughtName{get;set;}
    public String soughtStatus{get;set;}
    
    public List<String> soughtStatusList{get;set;}
    public List<SelectOption> paginationSizeOptions{get;set;}
    
    public Job_Advertisement__c jobAdvertisement{get;set;}
        
    public JobAdvertisementController(){
        jobAdvertisement = new Job_Advertisement__c();
        createPaginationOptions();
    }
    
    public void createPaginationOptions(){
        size=10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));
    }
    
    public void searchByStatus(){
        String temporaryStatus = jobAdvertisement.Temporary_Status__c;
        List<String> temporaryStatusList = new List<String>();
        if(temporaryStatus != null){
            temporaryStatusList = temporaryStatus.split(';');
        }
        soughtStatusList = new List<String>();
        for(String status : temporaryStatusList){
            soughtStatusList.add(status);
        }
		soughtStatus = String.join(soughtStatusList,',');
        System.debug(soughtStatus);
    }
    
    public List<Job_Advertisement__c> getJobAdvertisementsByParameters(){
		List<String> filters = new List<String>();
        
        if(String.isNotBlank(soughtName)) {
        	filters.add('Name LIKE \'%' + String.escapeSingleQuotes(soughtName)+'%\'');
    	}
        if(String.isNotBlank(soughtStatus)) {
        	filters.add('Status__c =: soughtStatusList');
    	}
        if(equalSalary != null && equalSalary != 0) {
    		filters.add('(MIN_Salary__c <=: equalSalary AND MAX_Salary__c >=: equalSalary)');
		}
		if(notEqualSalary != null && notEqualSalary != 0) {
    		filters.add('(Salary__c != null AND (MIN_Salary__c >: notEqualSalary OR MAX_Salary__c <: notEqualSalary))');
		}
		if(lessThanSalary != null && lessThanSalary != 0) {
    		filters.add('(Salary__c != null AND MAX_Salary__c <: lessThanSalary)');
		}
        if(lessThanEqualSalary != null && lessThanEqualSalary != 0) {
    		filters.add('(Salary__c != null AND MAX_Salary__c <=: lessThanEqualSalary)');
		}
        if(moreThanSalary != null && moreThanSalary != 0) {
        	filters.add('(Salary__c != null AND MIN_Salary__c >: moreThanSalary)');
    	}
        if(moreThanEqualSalary != null && moreThanEqualSalary != 0) {
        	filters.add('(Salary__c != null AND MIN_Salary__c >=: moreThanEqualSalary)');
    	}
        return Database.query('SELECT Id, Name, Location__c, Description__c, Salary__c, Skills_Required__c, Education__c, Manager_Name__c, Status__c FROM Job_Advertisement__c'+
                             (filters.isEmpty()?'':' WHERE ' + String.join(filters,' AND ')));
    }

    public ApexPages.StandardSetController setController {
        get {
            if(setController == null) {                
                setController = new ApexPages.StandardSetController(getJobAdvertisementsByParameters());
                setController.setPageSize(size);  
                noOfRecords = setController.getResultSize();
            }
            return setController;
        }
        set;
    }
     
    public PageReference refreshPageSize() {
        setController.setPageSize(size);
        noOfRecords = setController.getResultSize();
        return null;
    }
 
    public List<Job_Advertisement__c> getJobAdvertisementList() {  //Это и есть JobAdvertisementList в VF
        return (List<Job_Advertisement__c>) setController.getRecords();
    }
    
    public Pagereference searchByParameters() {
        setController = new ApexPages.StandardSetController(getJobAdvertisementsByParameters());
        refreshPageSize();
        return null;
	}  
}