temp/objects/Resume_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Resume__c</referenceTo>
        <relationshipLabel>Resume Junctions</relationshipLabel>
        <relationshipName>Resume_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>ExternalID</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Job_Advertisement__c</referenceTo>
        <relationshipLabel>Resume Junctions</relationshipLabel>
        <relationshipName>Resume_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resume Junction</label>
    <nameField>
        <displayFormat>ResumeJunction-{0000}</displayFormat>
        <label>Resume Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EndpointResumeJunction.cls
@RestResource(urlMapping='/resumeJunctionEndpoint/*')
global with sharing class EndpointResumeJunction {
    
    @HttpGet
    global static List<Resume_Junction__c> getResumeJunction(){
        RestRequest req = RestContext.request;
        Integer rowsToSkip = Integer.valueOf(req.requestURI.substring(req.requestURI.lastIndexOf('/')+1));
        
        List<Resume_Junction__c> resumeJunctionList;
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        try{
            resumeJunctionList = [SELECT Candidate__c, Position__c, ExternalID__c
                          		  FROM Resume_Junction__c
                          		  LIMIT 100
                                  OFFSET : rowsToSkip];
            res.responseBody = Blob.valueOf(JSON.serialize(resumeJunctionList));
            res.statusCode = 200;
        } catch(QueryException e){
            res.responseBody = Blob.valueOf(e.getMessage());
            res.statusCode = 400;
        } catch(Exception e) {
            res.responseBody = Blob.valueOf(String.valueOf(e) + '\n' + e.getStackTraceString());
            res.statusCode = 500;
        }
        return resumeJunctionList;
    } 
}