temp/objects/Resume__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Info__c</fullName>
        <label>Additional Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currently_Employed__c</fullName>
        <formula>IF(TEXT(Status__c) == &apos;Employed&apos;, TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currently Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>LEFT(Full_Name__c,FIND(&quot; &quot;, Full_Name__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>RIGHT(Full_Name__c, LEN(Full_Name__c) - FIND(&quot; &quot;, Full_Name__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Photo_Code__c</fullName>
        <label>Photo Code</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Photo_PathOnClient__c</fullName>
        <label>Photo PathOnClient</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_Title__c</fullName>
        <label>Photo Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Resume</label>
    <nameField>
        <displayFormat>Resume-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EndpointResume.cls
@RestResource(urlMapping='/resumeEndpoint/*')
global with sharing class EndpointResume {
    
    @HttpGet
    global static List<Resume__c> getResume(){
        RestRequest req = RestContext.request;
        RestResponse res = new RestResponse();
        RestContext.response = res;
        List<Resume__c> resumeList;
                
        Integer lastIndex = 0;  //последний индекс из коллаута
        Integer step = 200;
        Integer listSize = 400;  //размер одного запроса из коллаута
        
        Database.QueryLocator q = Database.getQueryLocator([SELECT First_Name__c, Last_Name__c, Age__c, Salary__c, Email__c, Phone__c, Currently_Employed__c,
                                                            Additional_Info__c, Photo_Code__c, Photo_Title__c, Photo_PathOnClient__c
                          									FROM Resume__c]);
        Database.QueryLocatorIterator iterator =  q.iterator();  //итерация по кверилокатору
       
        List<Resume__c> totalResumeList = new List<Resume__c>();  //присваиваем локатор листу резюме (его аналог, но в листе)
        while (iterator.hasNext()) {
            Resume__c resume = (Resume__c)iterator.next();
            totalResumeList.add(resume);    
        }  
        
        Integer n = listSize/step;
        List<Resume__c> currentResumeList;
        
        for(Integer j=1; j<=n; j++){
            currentResumeList = new List<Resume__c>();
            step = step * j;
            
        	for(Integer i=lastIndex; i<step; i++){
            	currentResumeList.add(totalResumeList.get(i));
        	}
            try{
                res.responseBody = Blob.valueOf(JSON.serialize(currentResumeList));
                res.statusCode = 200;
            } catch(QueryException e){
            	res.responseBody = Blob.valueOf('Error 400:  ' + e.getMessage());
            	res.statusCode = 400;
        	} catch(Exception e) {
            	res.responseBody = Blob.valueOf('Error 500:  ' + String.valueOf(e) + '\n' + e.getStackTraceString());
            	res.statusCode = 500;
        	}
            lastIndex = lastIndex + step;
            //return currentResumeList;
        }
        
        /*if((lastIndex + listSize) <= totalResumeList.size()) {
            last_i = lastIndex + listSize;
        } else{
            last_i = totalResumeList.size();
        }
        
        System.debug('last_i:  ' + last_i);
        
        for(Integer i=lastIndex; i<last_i; i++) {
            currentResumeList.add(totalResumeList.get(i));
            System.debug('currentResumeList.size():  ' + currentResumeList.size());	
        }*/
        
		
        
        
        /*try{
            Id reqId = RestContext.request.params.get('Id');
  			//if(reqId != null) {
    			resumeList = [SELECT First_Name__c, Last_Name__c, Age__c, Salary__c, Email__c, Phone__c, Status__c,
                          	   		 Additional_Info__c, Photo_Code__c, Photo_Title__c, Photo_PathOnClient__c
                        	  FROM Resume__c
                        	 // WHERE Id > :reqId
                        	 // ORDER BY Id
                        	 // LIMIT 2000
                             ];
            } else {
                resumeList = [SELECT First_Name__c, Last_Name__c, Age__c, Salary__c, Email__c, Phone__c, Currently_Employed__c,
                          		     Additional_Info__c, Photo_Code__c, Photo_Title__c, Photo_PathOnClient__c
                              FROM Resume__c
                              ORDER BY Id
                              LIMIT 200];
  			}
            //res.responseBody = Blob.valueOf(JSON.serialize(currentResumeList));
            res.statusCode = 200;
        } catch(QueryException e){
            res.responseBody = Blob.valueOf('Error 400:  ' + e.getMessage());
            res.statusCode = 400;
        } catch(Exception e) {
            res.responseBody = Blob.valueOf('Error 500:  ' + String.valueOf(e) + '\n' + e.getStackTraceString());
            res.statusCode = 500;
        }*/
        return currentResumeList;
    }
}